// Prompt source for Scenario move sprite grids.
// Keep this data-only; do not import executable generator scripts.

export const VISUAL_HINTS = {
  // Existing hints copied from scripts/generate-move-icons.mjs.
  encircle: 'arrows circling inward from all directions, surrounding a center point',
  'throw-away': 'a hand flinging something away with a careless toss arc',
  topple: 'a figure being knocked sideways with impact lines and dust',
  fire: 'a cute cartoon cannon firing a cannonball with a puff of smoke',
  pull: 'a hand pulling with a rope, taut motion lines',
  'wash-away': 'a rushing wave sweeping things away with foam and spray',
  'step-on': 'a foot stomping down hard with a ground-crack impact star',
  wound: 'a red scratch wound mark with small drops',
  tear: 'fabric or paper being torn apart with ragged edges',
  launch: 'a rocket projectile launching upward with exhaust flames',
  wash: 'water splashing in a cleaning swirl',
  bury: 'a mound of dirt with something half-buried, shovel marks',
  demolish: 'crumbling brick wall breaking apart with debris flying',
  pour: 'liquid pouring down from a tilted vessel',
  thrust: 'a spear thrusting forward with a sharp impact point',
  overflow: 'water overflowing from a cup or container, splashing out',
  shoot: 'a bow releasing an arrow with speed lines',
  assault: 'multiple rapid strike impacts in a burst pattern',
  roast: 'flames licking upward around a spit, cooking fire',
  beat: 'a drum being struck with drumsticks, impact rings',
  penetrate: 'an arrow piercing clean through a wooden target',
  slice: 'a clean diagonal blade cut with a bright energy trail',
  snap: 'sharp jaws snapping shut quickly with a click effect',
  ruin: 'ancient crumbling ruins with dust clouds rising',
  rip: 'something being ripped apart with force, pieces flying',
  spin: 'a spinning vortex motion with circular speed lines',
  'swallow-up': 'a whirlpool vortex sucking things inward, spiral',
  grasp: 'a fist clenching tight with grip pressure lines',
  sting: 'a sharp bee stinger needle piercing downward with a bright impact star and speed lines',
  dig: 'a small shovel biting into a mound of dirt with soil chunks flying outward',
  dash: 'horizontal speed lines with a motion blur swoosh',
  persevere: 'a raised fist glowing with determination, small sparkle',
  call: 'a megaphone projecting bold sound waves outward',
  teach: 'a pointer wand tapping a glowing star, knowledge sparkle',
  approach: 'footprint trail with forward-pointing arrows',
  hurry: 'a clock face with spinning hands and speed lines',
  'stand-up': 'an upward arrow figure rising with bold upward energy',
  'jump-out': 'bursting outward from a surface with radial speed lines',
  exceed: 'an upward arrow smashing through a ceiling barrier, shards flying',
  fly: 'spread feathered wings with wind gusts beneath',
  leap: 'an upward arc trajectory with spring coil lines at the base',
  sparkle: 'brilliant multi-pointed sparkle burst with star shapes radiating',
  challenge: 'two crossed swords with a spark at the intersection',
  extend: 'an arm or beam extending outward with reach arrows stretching forward',
  pray: 'two hands clasped together in prayer with a soft halo glow above',
  stretch: 'an elastic shape stretching outward with extension arrows',
  stack: 'glowing blocks stacking upward, three layers high',
  chirp: 'a musical note with a small cute bird beak beside it',
  speak: 'a speech bubble with small sound wave lines',
  rage: 'an angry red aura burst with comic fury vein marks',
  suffer: 'a pained swirl of dark purple energy, anguished',
  shake: 'zigzag vibration lines shaking back and forth',
  doubt: 'a large question mark with a narrowed suspicious eye',
  stare: 'two intense glowing eyes staring forward with focus lines',
  tremble: 'a shivering shape outline with rapid vibration marks',
  touch: 'a fingertip touching a surface with a soft ripple ring',
  cry: 'large teardrops falling from sad eyes',
  shout: 'a wide-open mouth shouting with bold concentric sound rings',
  trick: 'a magician top hat with sneaky sparkles and a hidden card',
  tie: 'thick ropes tied in a tight restricting knot',
  abandon: 'a broken chain link falling apart with pieces scattering',
  restrict: 'a padlock snapping shut with a metallic gleam',
  extinguish: 'a candle flame being blown out, wisps of smoke curling up',
  freeze: 'ice crystals forming with cold mist spreading outward',
  'pin-down': 'a hand pressing firmly downward with an impact star beneath',
  catch: 'a swooping net closing around something',
  melt: 'something dripping and melting with wavy heat lines rising',
  cure: 'a glowing green cross symbol with gentle sparkles around it',
  support: 'open palms cradling upward with a soft warm glow between them',
  'hand-over': 'two hands passing a small glowing orb between them',
  drink: 'a potion bottle being tilted with liquid pouring out',
  help: 'a helping hand reaching out with a warm golden glow',
  heal: 'a heart shape with green healing sparkles and soft light',
  rest: 'a peaceful cloud with Zzz letters floating above',
  sleep: 'a crescent moon with Zzz and tiny stars',
  warm: 'a warm orange glow orb with gentle heat waves rising upward',
  recover: 'a circular refresh arrow symbol with sparkles around it',
  sprout: 'a bright green sprout with two leaves unfurling from soil',
  sit: 'a soft round cushion compressing downward with settling motion lines',
  hide: 'a figure silhouette ducking behind a bush, half-hidden',
  protect: 'a glowing energy shield dome with protective light',
  enlarge: 'expanding outward arrows radiating from a center point',
  guard: 'a sturdy metal shield with a defensive cross emblem',
  cover: 'a protective dome or canopy sheltering from above',
  submerge: 'something sinking below a water surface line with bubbles rising',
  revolve: 'an orbiting ring spinning around a central point',
  stance: 'two firmly planted feet in a wide grounded stance, solid base',
  preserve: 'a glass jar or protective bubble containing a glowing object',
  dodge: 'a swift sidestep motion with a fading afterimage trail',
  endure: 'a solid rock standing firm against crashing waves',
  conceal: 'a cloak fading into invisibility with shimmering sparkle edges',
  float: 'a feather floating gently upward with small air bubbles',
  steal: 'a sneaky shadowy hand swiping with a quick-grab motion line',
  pluck: 'fingers plucking a feather or string with a twang effect',
  inhale: 'a swirling vortex of air being breathed inward, suction spiral',
  performance: 'musical notes swirling around instruments, a lively concert effect',

  // Legacy/core action hints needed when the action sprite directory is sparse.
  strike: 'a fist or weapon striking with a bright impact burst',
  flame: 'a bright orange flame with a glowing core',
  burn: 'flames burning intensely around a simple target',
  cut: 'a sharp blade making a clean diagonal cut',
  write: 'a brush pen writing a bold stroke on paper, no letters',
  read: 'an open book glowing with knowledge sparkles, no text',
  erase: 'an eraser wiping away a dark mark, no letters',
  dance: 'graceful dancing motion shown as swirling ribbons and foot marks',
  shine: 'bright light rays shining outward from a central glow',
  'blow-away': 'a powerful gust blowing leaves and dust away',
  curse: 'a dark skull-shaped aura with purple energy',
  bite: 'sharp teeth biting down with a small impact burst',
  destroy: 'a crumbling object breaking into debris',
  hit: 'a simple impact star where a small object is struck',
  throw: 'an arm throwing an object along a curved motion arc',
  swing: 'a sweeping weapon swing shown as a broad motion arc',
  capture: 'a net closing around a simple target shape',
  seize: 'a hand grabbing tightly with pressure lines',
  scratch: 'three sharp claw scratch marks with tiny sparks',
  slash: 'a sharp blade slash with a bright energy trail',
  rampage: 'wild destructive energy crashing through debris',
  punch: 'a powerful fist punching forward with speed lines',
  dive: 'a downward diving motion into water or shadow',
  smash: 'a fist smashing down with shattered fragments',
  scorch: 'a blackened scorch mark with orange embers',
  illuminate: 'a beam of light illuminating a dark area',
  glare: 'fierce glowing eyes glaring with focus lines',
  crush: 'a heavy weight crushing downward with cracks',
  bind: 'chains or ropes binding a simple target tightly',
  tighten: 'a rope loop squeezing tighter around a target',
  lick: 'a tongue licking with a quick curved motion line',
  pierce: 'a sharp point piercing into a simple target',
  bounce: 'a ball bouncing upward with springy motion lines',
  kick: 'a leg kicking forward with a strong impact burst',
  block: 'a solid barrier blocking incoming arrows',

  // Missing move hints curated for the 2026-05-17 missing-action-sprite pass.
  gnaw: 'sharp teeth gnawing into a small branch, with tiny wood chips',
  'finishing-blow': 'a decisive final impact burst striking a cracked target',
  twist: 'two curved arrows twisting a flexible band into a spiral',
  impact: 'a heavy collision starburst against a stone surface',
  'heavy-punch': 'a large fist punching forward with dense impact lines',
  'coil-around': 'a vine or rope coiling around a simple target shape',
  'knock-down': 'a blocky target falling backward from a strong hit',
  'cut-down': 'a downward blade slash cutting through a simple target',
  rend: 'two crossing claw slashes tearing through cloth',
  restrain: 'glowing bands tightening around a simple target shape',
  mince: 'many small chopping cuts scattering tiny fragments',
  split: 'a cracked object splitting cleanly into two halves',
  envelop: 'soft green energy wrapping around a center point like a cocoon',
  parry: 'a small shield deflecting a blade with a bright spark',
  slam: 'a heavy object slamming down with dust and shock lines',
  'crush-flat': 'a massive weight flattening a target with ground cracks',
  spew: 'a burst of liquid or energy spraying outward from a mouth-like shape',
  'spit-out': 'a small projectile being spat out with sharp speed lines',
  spit: 'a quick droplet projectile flying forward with motion lines',
  absorb: 'green energy streams being drawn into a central orb',
  gust: 'a strong wind gust curling forward with leaves swept along',
  summon: 'a glowing magic circle calling forth a small light shape',
  growl: 'jagged sound waves from a fierce mouth silhouette',
  erupt: 'fire and smoke erupting upward from a cracked ground vent',
  flank: 'curved arrows moving around the side of a target',
  break: 'a cracked wall block breaking into chunks',
  seal: 'a glowing lock sigil closing over a simple target silhouette',
  extract: 'a hand pulling a glowing shard out from stone',
  'rip-apart': 'two hands pulling torn fabric apart with fragments flying',
  'pull-apart': 'two arrows pulling connected pieces away from each other',
  rebound: 'a ball bouncing off a surface with return arrows',
  yell: 'bold jagged sound waves bursting from an open mouth',
  smack: 'an open palm impact with a comic burst shape',
  'throw-down': 'a hand throwing an object downward into the ground',
  'hold-down': 'a hand pressing a target down with downward arrows',
  surge: 'a rising wave rushing forward in a powerful swell',
  squash: 'a heavy downward press squashing a soft target shape',
  pinch: 'two pincers closing inward on a small target',
  'overhead-swing': 'a weapon swinging down from above in a bright arc',
  'shake-off': 'a target shaking loose with broken bands flying away',
  'shake-away': 'a sweeping shake motion pushing particles outward',
  grab: 'a hand grabbing a small object with pressure lines',
  clench: 'a fist clenching tightly with small pressure sparks',
  jolt: 'a target jolted by zigzag shock lines',
  sway: 'a wavy silhouette leaning side to side with motion trails',
  fling: 'an object flung in a high arc from a hand',
  hurl: 'a heavy object thrown forward with strong speed lines',
  scatter: 'small leaves or shards scattering outward in many directions',
  'cut-apart': 'a clean blade cut separating a cord into two pieces',
  sever: 'a single sharp slash cutting through a rope',
  sing: 'musical notes and sound rings radiating from a small mouth',
  sink: 'a shape sinking below a water line with bubbles rising',
  drench: 'water pouring over a target with splashes',
  'wipe-away': 'a sweeping cloth or wave erasing a dark mark',
  whirl: 'a water vortex spinning in a tight spiral',
  char: 'a darkened burnt mark with small orange embers',
  blaze: 'a tall roaring flame with bright orange core',
  ignite: 'a spark lighting a small flame on kindling',
  'take-aim': 'a crosshair locking onto a simple target',
  pilfer: 'a sneaky hand lifting a small coin with motion lines',
  'shatter-apart': 'a crystal bursting into many sharp fragments',
  stab: 'a dagger point striking forward with a small impact star',
  'pierce-through': 'a spear passing completely through a target',
  skewer: 'a pointed spear pinning several small shapes in a line',
  shove: 'two hands pushing a target away with force lines',
  poke: 'a fingertip or stick poking a small target with a tiny spark',
  charge: 'a rushing arrow-shaped impact driving forward',
  'tie-up': 'rope loops tying a target into a tight bundle',
  unleash: 'a burst of stored energy shooting out from a hand',
  threaten: 'a dark warning aura with sharp triangular danger marks',
  pounce: 'a leaping claw silhouette arcing toward a target',
  run: 'fast feet with horizontal speed lines',
  trample: 'multiple heavy footprints stomping across cracked ground',
  stomp: 'one foot stomping down with a strong impact burst',
  'stand-firm': 'two planted feet braced against incoming wind',
  'guard-stance': 'a shield and planted feet in a defensive pose',
  'roll-over': 'a round boulder rolling over with curved motion arrows',
  reverberate: 'concentric sound waves shaking the ground',
  chase: 'footprints and forward arrows pursuing a small target',
  'drive-off': 'a sweeping hand and arrows pushing a target away',
  corner: 'arrows pressing a target into a corner shape',
  flee: 'small feet sprinting away with dust puffs',
  escape: 'a figure slipping through an opening with motion lines',
  interrupt: 'a barrier line cutting across incoming motion lines',
  flash: 'a sudden bright starburst with sharp light rays',
  imprison: 'a glowing cage closing around a simple target',
  fight: 'two crossed weapons colliding with a central spark',
  obstruct: 'a blocky barrier stopping forward arrows',
  'rain-down': 'many droplets or arrows falling from above',
  'take-flight': 'wings launching upward with wind beneath',
  'jump-down': 'a downward leap arc landing with a dust burst',
  'bite-into': 'sharp teeth biting deep into a simple target edge',
};

export function getMoveVisualHint(slug) {
  return VISUAL_HINTS[slug] || null;
}

export function buildMoveGridPrompt(batch) {
  if (!Array.isArray(batch) || batch.length !== 9) {
    throw new Error('buildMoveGridPrompt requires exactly 9 batch entries');
  }

  const layoutLines = [];
  for (let r = 0; r < 3; r++) {
    const rowItems = batch.slice(r * 3, (r + 1) * 3);
    const descriptions = rowItems.map((item, i) => `(${r * 3 + i + 1}) ${item.hint}`);
    layoutLines.push(`Row ${r + 1}: ${descriptions.join(', ')}`);
  }

  return [
    'Use the same art style as the reference images. These icons are for the same game.',
    '',
    'Draw EXACTLY 9 compact RPG ability icons arranged in a 3x3 layout on a flat white background (#FFFFFF).',
    'These are NOT characters or creatures. They are symbolic skill icons and vocabulary flashcard icons for an RPG.',
    'Each icon should communicate the action visually to a new language learner.',
    '',
    'IMAGE FORMAT:',
    '- Square image, 1024x1024',
    '- EXACTLY 3 columns and EXACTLY 3 rows',
    '- EXACTLY one icon in each cell',
    '- Do not add extra items, extra columns, extra rows, props, plates, bowls, background objects, borders, or dividers',
    '',
    'Layout (3 rows, 3 columns):',
    ...layoutLines,
    '',
    'LAYOUT:',
    '- Place each icon in an evenly-spaced 3x3 arrangement',
    '- DO NOT draw any grid lines, borders, dividers, or frames',
    '- The entire background must be solid flat white (#FFFFFF) with nothing else on it',
    '- Each icon must be fully contained in its area, not overlapping neighbors',
    '',
    'ART STYLE:',
    '- Fully opaque icon pixels with crisp boundaries for Scenario Photoroom background removal',
    '- No semi-transparent pixels, no soft feathered edges against the background',
    '- No text, no labels, no letters, no kana, no numbers, no UI frames',
    '- Each icon should be instantly recognizable as the concept it represents',
    '- Front-facing, centered in each cell',
    '- Small, compact designs that read well at 128x128 pixels',
  ].join('\n');
}
