import { describe, it } from 'node:test';
import assert from 'node:assert';
import { ROOM_TYPES, generateAreaRooms, createRoom, WORDS_PER_DISCOVERY, getRoomEntryNarration, getRoomActions } from '../../../src/game/rooms.js';

describe('Word Discovery Room', () => {
  // Koto2 generateAreaRooms no longer produces wordDiscovery rooms (disabled room type),
  // but the room type constant and createRoom still work for direct creation.
  it('wordDiscovery is not generated by Koto2 30-room generator', () => {
    const rooms = generateAreaRooms('okunomori');
    const hasWD = rooms.some(r => r.type === 'wordDiscovery');
    assert.strictEqual(hasWD, false, 'wordDiscovery should not appear in Koto2 room generation');
  });

  it('should create wordDiscovery room with correct structure via createRoom', () => {
    const room = createRoom('wordDiscovery', 'okunomori', 2, 5);
    assert.strictEqual(room.type, 'wordDiscovery');
    assert.deepStrictEqual(room.wordDiscovery, {
      wordsToLearn: 2,
      wordsLearned: 0,
      wordIds: [],
      completed: false
    });
  });
});

describe('Word Discovery Room Narration', () => {
  it('should return entry narration for wordDiscovery room', () => {
    const room = {
      type: 'wordDiscovery',
      floor: 1,
      roomNumber: 2,
      totalRooms: 5
    };
    const narration = getRoomEntryNarration(room);
    assert.ok(narration.includes('エリア2/5'), 'Narration should contain room number');
  });

  it('should return empty actions for wordDiscovery room', () => {
    const room = {
      type: 'wordDiscovery',
      interacted: false,
      wordDiscovery: { completed: false }
    };
    const actions = getRoomActions(room);
    // No action buttons - flash cards appear automatically
    assert.strictEqual(actions.find(a => a.id === 'proceed'), undefined, 'proceed should not be available');
  });

  it('should return proceed action when wordDiscovery is completed', () => {
    const room = {
      type: 'wordDiscovery',
      interacted: true,
      wordDiscovery: { completed: true }
    };
    const actions = getRoomActions(room);
    assert.ok(actions.find(a => a.id === 'proceed'), 'proceed should be available after completion');
  });
});
