[phases.setup]
nixPkgs = ["nodejs_20", "python3", "python3Packages.pip"]

[phases.python]
cmds = ["python3 -m pip install --break-system-packages -r requirements.txt"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
